version: "3"
services:
  staging:
    build: ./Dockerfiles/5.3 # for testing compilation in the university gcc version
    volumes:
      - .:/app
  testing:
    build: ./Dockerfiles/8.2 # for the gtests
    volumes:
      - .:/app
