version: "3"
services:
  staging:
    hostname: staging
    build: ./Dockerfiles/5.3 # for testing compilation in the university gcc version
    volumes:
      - .:/app
      
  
  testing:
    hostname: testing
    build: ./Dockerfiles/8.2 # for the gtests
    volumes:
      - .:/app

